const dailyQuestions = [
  '¿Qué se te antoja hoy: café, tacos o pan dulce?',
  '¿Qué desayuno se te antoja para empezar el día?',
  '¿Eres más de café caliente o café frío?',
  '¿Qué prefieres para la tarde: algo dulce o algo salado?',
  '¿Cuál es tu antojo favorito para un día lluvioso?',
  '¿Qué bebida pedirías para refrescarte hoy?',
  '¿Qué se te antoja más: una nieve o una paleta?',
  '¿Qué prefieres para cenar: algo ligero o algo bien servido?',
  '¿Con qué salsa acompañas tus tacos?',
  '¿Qué antojito mexicano nunca rechazas?',
  '¿Qué prefieres: tortillas de maíz o de harina?',
  '¿Cuál es tu pan dulce favorito?',
  '¿Con qué acompañas mejor un café?',
  '¿Qué prefieres: desayuno dulce o desayuno salado?',
  '¿Qué fruta se te antoja hoy?',
  '¿Cuál es tu agua fresca favorita?',
  '¿Qué sabor de nieve elegirías ahora mismo?',
  '¿Eres más de enchiladas o chilaquiles?',
  '¿Qué prefieres para compartir: pizza o una buena botana?',
  '¿Cuál es tu comida casera favorita?',
  '¿Qué platillo te recuerda a tu infancia?',
  '¿Qué prefieres: sopa calientita o algo recién salido del comal?',
  '¿Qué ingrediente extra le pondrías a tus tacos?',
  '¿Cuál es tu hora favorita para tomar café?',
  '¿Qué se te antoja más en un día de calor?',
  '¿Qué se te antoja más en un día frío?',
  '¿Qué prefieres: chocolate caliente o atole?',
  '¿Cuál es tu guisado favorito para una comida corrida?',
  '¿Qué prefieres: comida picosa o sin picante?',
  '¿Qué botana elegirías para una tarde de películas?',
  '¿Cuál es tu postre mexicano favorito?',
  '¿Qué prefieres: flan o pastel?',
  '¿Qué sabor de aguas frescas combinarías con la comida de hoy?',
  '¿Qué desayuno recomendarías a alguien que viene de visita?',
  '¿Qué platillo podrías comer varias veces por semana?',
  '¿Qué prefieres: tacos dorados o tacos blanditos?',
  '¿Con qué acompañas unos buenos frijoles?',
  '¿Qué se te antoja para una noche tranquila?',
  '¿Cuál es tu combinación favorita para una torta?',
  '¿Qué prefieres: elote o esquites?',
  '¿Cuál es tu antojo favorito para compartir?',
  '¿Qué bebida va mejor con unos tacos?',
  '¿Qué prefieres: cocinar en casa o pedir algo rico?',
  '¿Qué platillo te gustaría aprender a preparar?',
  '¿Cuál es tu desayuno rápido favorito?',
  '¿Qué prefieres: fruta con chile o fruta natural?',
  '¿Qué sabor de nieve siempre eliges?',
  '¿Qué se te antoja después de una caminata?',
  '¿Qué prefieres: una comida larga con amigos o algo rápido?',
  '¿Cuál es tu antojito favorito para la tarde?',
  '¿Qué prefieres: arroz rojo o arroz blanco?',
  '¿Qué guarnición no puede faltar en tu plato?',
  '¿Qué tipo de taco pedirías primero?',
  '¿Qué prefieres: quesadilla con queso o sin queso?',
  '¿Cuál es tu sabor de agua fresca para acompañar el pan?',
  '¿Qué postre compartirías con alguien especial?',
  '¿Qué comida te pone de buen humor?',
  '¿Qué prefieres: pan recién hecho o tortillas recién hechas?',
  '¿Cuál es tu combinación favorita para una nieve?',
  '¿Qué se te antoja para un desayuno de domingo?',
  '¿Qué prefieres: una tarde de café o una tarde de nieve?',
  '¿Cuál es tu comida favorita para celebrar algo?',
  '¿Qué tipo de salsa prefieres: verde, roja o de árbol?',
  '¿Qué prefieres: algo crujiente o algo suave?',
  '¿Cuál es tu antojo favorito cuando sales con amigos?',
  '¿Qué platillo te gustaría volver a probar?',
  '¿Qué prefieres: una comida con mucho queso o con mucha salsa?',
  '¿Cuál es tu bebida favorita para acompañar el desayuno?',
  '¿Qué se te antoja para una tarde de descanso?',
  '¿Qué prefieres: tamales dulces o salados?',
  '¿Cuál es tu relleno favorito para una gordita?',
  '¿Qué prefieres: una comida hecha en casa o probar algo nuevo?',
  '¿Qué ingrediente hace mejor cualquier torta?',
  '¿Cuál es tu desayuno favorito para llevar?',
  '¿Qué prefieres: café con leche o café negro?',
  '¿Qué sabor de pan dulce eliges primero?',
  '¿Qué se te antoja más para la comida de hoy?',
  '¿Cuál es tu antojo favorito de madrugada?',
  '¿Qué prefieres: tacos de guisado o tacos al carbón?',
  '¿Qué platillo te gustaría compartir con toda tu familia?',
  '¿Cuál es tu acompañamiento favorito para una carne asada?',
  '¿Qué prefieres: una bebida con hielo o al tiempo?',
  '¿Qué postre elegirías para cerrar una buena comida?',
  '¿Qué prefieres: desayunar temprano o hacer brunch?',
  '¿Cuál es tu combinación favorita de pan y bebida?',
  '¿Qué te gusta más: el primer café del día o el de la tarde?',
  '¿Qué se te antoja para una comida entre semana?',
  '¿Qué prefieres: un antojito pequeño o un plato completo?',
  '¿Cuál es tu forma favorita de comer aguacate?',
  '¿Qué ingrediente nunca falta en tu cocina?',
  '¿Qué prefieres: algo recién horneado o algo recién preparado?',
  '¿Cuál es tu platillo favorito para llevar de visita?',
  '¿Qué elegirías para una tarde de lluvia: café, chocolate o atole?',
  '¿Qué prefieres: una salsa tatemada o una salsa fresca?',
  '¿Cuál es tu antojo favorito para ver un partido?',
  '¿Qué te gustaría encontrar en una buena cafetería?',
  '¿Qué prefieres: comida tradicional o una combinación nueva?',
  '¿Cuál es el sabor que siempre te recuerda a casa?',
  '¿Qué se te antoja para darte un gusto hoy?',
  '¿Qué prefieres compartir hoy: café, tacos o pan dulce?',
];

const firstDropDay = Date.UTC(2026, 9, 5);

export function getDailyDropQuestion(date = new Date()) {
  const day = Date.UTC(date.getFullYear(), date.getMonth(), date.getDate());
  const daysSinceFirstDrop = Math.floor((day - firstDropDay) / 86_400_000);
  const index = ((daysSinceFirstDrop % dailyQuestions.length) + dailyQuestions.length) % dailyQuestions.length;
  return dailyQuestions[index];
}
